{
    "name": "Contract Management",
    "version": "19.0.1.0.0",
    "category": "Operations",
    "summary": "Basic contract management",
    "author": "Your Company",
    "license": "LGPL-3",
    "depends": ["base", "mail", "hr"],
    "post_init_hook": "post_init_hook",
    "assets": {
        "web.assets_backend": [
            "contract_management/static/src/js/many2many_binary_rename.js",
            "contract_management/static/src/scss/contract_management.scss",
            "contract_management/static/src/scss/contract_management_badge.scss",
            "contract_management/static/src/scss/contract_timeline.scss",
        ],
    },
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/reminder_defaults.xml",
        "data/contract_sequence.xml",
        "data/contract_cron.xml",
        "data/contract_status_cron.xml",
        "data/contract_expiring_cron.xml",
        "data/contract_activate_cron.xml",
        "data/contract_renew_cron.xml",
        "data/contract_ocr_cron.xml",
        "data/report_contract.xml",
        "views/attachment_rename_wizard.xml",
        "views/ocr_log_views.xml",
        "views/ocr_viewer_wizard.xml",
        "views/contract_cancel_wizard.xml",
        "views/contract_approval_wizard.xml",
        "views/contract_views.xml",
        "views/report_contract.xml",
        "views/config_views.xml",
        "views/menu.xml",
    ],
    "application": True,
    "installable": True,
}
